### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by taskinoz** [piotrwawrzyn/markupwriter#1]
I tried following the installation instructions but didn't find any on how to render the front end.

After trying to run the js file I got:

```
const renderedHtmlContainer = document.querySelector('.rendered-html');
                              ^

ReferenceError: document is not defined
```

**Comment by piotrwawrzyn** [comment]
Hey, sorry for my instructions not being clear - I will make sure to correct them later today.

1) Please make sure you have index.html and index.js file looking simmilar to this:

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <title>markupwriter - basic usage</title>
  </head>
  <body>
    <div class="rendered-html"></div>
    <div class="raw-html"></div>
  </body>
</html>
```

index.js
```
import MarkupWriter from 'markupwriter';

const renderedHtmlContainer = document.querySelector('.rendered-html');
const rawHtmlContainer = document.querySelector('.raw-html');
const htmlString = `
<div class="container">
	<h1>Hey there</h1>
	<p>This is some cool stuff going on here</p>
</div>
`;

const markupWriter = new MarkupWriter(renderedHtmlContainer, rawHtmlContainer, htmlString);

markupWriter.start()
```

2) You need to have some basic webpack configured to bundle the script, I will leave quick instructions just in case

`npm install --save-dev webpack`


webpack.config.js

```
const path = require('path');

module.exports = {
  entry: './index.js',
  output: {
    filename: 'index.bundle.js',
    path: path.resolve(__dirname, 'build')
  }
};
```

if you haven't installed webpack globally earlier

`npm install webpack -g`

and run webpack command to build

`webpack`


3) Now link the built script at the bottom of the body tag in the index.html file

`<script src="./build/index.bundle.js" type="text/javascript"></script>`

4) Run the index.html file in the browser enviroment

Please let me know if that helped!
