### ISSUE TITLE
MarkupWriter not defined

### ISSUE THREAD

**Issue by advaitju** [piotrwawrzyn/markupwriter#2]
You need to export an ES6 module rather than build for Node or Webpack.

**Comment by piotrwawrzyn** [comment]
Can you tell something more on that one? I'm not sure I can understand the issue.

**Comment by piotrwawrzyn** [comment]
I updated the readme file with new installation instructions, please check them out.

**Comment by advaitju** [comment]
I read your updated README. I assumed before you were using ES6 modules because you were importing from your index.js.
That's another way to use import in modern browsers without needing Webpack (see example code below). But either way works.
```
// MarkupWriter.js code
export default MarkupWriter;
```
```
<!-- index.html -->
<script type="module" src="./node_modules/markupwriter/build/index.js"></script>
<script type="module" src="./index.js"></script>
```
```
npm i -g serve
cd project
serve
```
Now your code can work without Webpack.
